### ISSUE TITLE
Check color usage

### ISSUE THREAD

**Issue by tiiavalt** [salabs/Epimetheus#131]
**Is your feature request related to a problem? Please describe.**
There are currently colors in the codebase that are not in Epimetheus' color palette.

**Describe the solution you'd like**
Incorrect colors should be replaced with Epimetheus' own colors.

**Additional context**
Let's also check that all the Epimetheus' color palette's colors are added as variables.

**Comment by koops9** [comment]
Some svg imports seem to have lost their color so fixing that in future pull request...
