### ISSUE TITLE
Add support for internationalization and localization

### ISSUE THREAD

**Issue by ville-friman-siili** [salabs/Epimetheus#30]
**Is your feature request related to a problem? Please describe.**
Currently texts shown on pages are hard coded as English. To add support other languages these text should be parametrized. UI doesn't contain much text currently so this should be quite easy task to implement now.  

**Describe the solution you'd like**
There are probably multiple libraries to solve this problem. I don't have enough experience to recommend specific library. Default language can be English but if the user changes the language the new one should become the default language for that user.

**Describe alternatives you've considered**
There really isn't an alternatives for this.

**Additional context**
None.

**Comment by nikamani** [comment]
i18 is probably the way to go

https://react.i18next.com/
https://github.com/i18next/react-i18next
