### ISSUE TITLE
Sticky headers for tables

### ISSUE THREAD

**Issue by tfrisk** [salabs/Epimetheus#5]
Long tables can be hard to navigate when headers are not visible.
It could be easier to scroll the tables if headers would be visible while scrolling.

**Comment by vade5g** [comment]
Also suggestion to this feature related to the sticky headers. There could be a possibility to hover the metadata of a single build when hovering on top of the build number. If not like that, I'd love to get the possibility of seeing the metadata of builds before opening them on the history page.
