### ISSUE TITLE
Feature: Team page

### ISSUE THREAD

**Issue by tfrisk** [salabs/Epimetheus#7]
**Is your feature request related to a problem? Please describe.**
To realize the concept of teams, there should be a top level view for teams.

**Describe the solution you'd like**
We should have a page to show what teams are present in the selected system and what other data is assigned to those teams.

**Additional context**
This needs to be specified further before implementation. Probably has some effect on user navigation so it should be discussed with a designer.

**Comment by tfrisk-s** [comment]
**Brief specification**

Url navigation: Format `/team/NAME/`. Teams don't have id, only name string)

Main content:

- List of teams and series assigned to them.
- Series should have timestamp visible that shows their latest update time.
- Series should have link to their history page.

Example:

Team "Siili Kärmes"
- series 3, timestamp, link to /history/series/3
- series 2, timestamp, link to /history/series/2
- series 1, timestamp, link to /history/series/1

Notes:

- System could have tens of teams and thousands of series. It is important to filter out inactive series from default views to prevent clutter.
- Series should be listed in update order, most recently updated first.
